version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  synchronization:
    build:
      context: src/synchronization

  ml_model:
    build:
      context: src/ml_model
    ports:
      - '8080:8080'

  app:
    build: .
    depends_on:
      - mongodb
      - ml_model